import { StyleSheet } from "react-native";
export const style = StyleSheet.create({
    container:{
        flex:1,
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#0f0f0f",
        width:"auto",
    },
    box_container:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        borderStyle:"solid",
        margin:10,
        borderWidth:5,
        borderRadius:15,
        borderColor:"#3f3f3f",
        backgroundColor:"#3f3f3f"
    },
    box_col_divider:{
        flexDirection:"column",
        justifyContent:"center",
        alignItems:"flex-start",
    },
    box_row_divider:{
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
    },
    header:{
        fontSize:25,
        color:"#FFFFFF",
        fontWeight:"bold",
        margin:40,
        textAlign:"center",
        
    },
    paragraphHeader:{
        fontSize:25,
        marginTop:5,
        marginLeft:5,
        color:"#FFFFFF",
        textAlign:"left",
        fontWeight:"bold"
    },
    paragraph:{
        fontSize:15,
        color:"#ffffff7e",
        marginBottom:10,
        marginLeft:5,
        textAlign:"left",
    },
    image:{
        width:60,
        height:60,
        margin:10,
        borderRadius:100,
    }, 
    delbtn:{
        backgroundColor:"#FF0000AA",
        borderWidth:2,
        fontSize:15,
        textAlign:"center",
        textAlignVertical:"center",
        borderRadius:5,
        borderColor:"#cc0c00",
        color:"#FFFFFF",
        margin:10,
        width:50,
        height:40,
    },
    addbtn:{
        backgroundColor:"#00FF00AA",
        borderWidth:2,
        fontSize:15,
        textAlign:"center",
        textAlignVertical:"center",
        borderRadius:5,
        borderColor:"#00bd00ff",
        color:"#000000",
        margin:10,
        width:80,
        height:40,
    },
    textbox:{
        height:40,
        backgroundColor:"#ffffff48",
        borderWidth:3,
        borderColor:"#6b6b6b8c",
        borderRadius:10,
        marginLeft:10,
        marginTop:10,
        marginBottom:5,
        width:200,

    }
});